"""Level id -> display name, extracted from the game's LevelTypes table."""
_RAW = {
"1": "Twilight Grove",
"2": "Brawlhaven",
"3": "Grumpy Temple",
"4": "Small Twilight Grove",
"6": "Random",
"7": "The Great Hall",
"8": "World's End Kung Foot",
"10": "Enchanted Forest Arena",
"11": "Kings Pass",
"12": "Small Kings Pass",
"13": "Small Kings Pass Test",
"14": "Small Kings Pass Test2",
"15": "Brawlball Arena",
"16": "Bombsketball Arena",
"17": "Dodgebomb Arena",
"18": "Jikoku",
"19": "Enchanted Forest",
"20": "Beachbrawl Arena",
"22": "Titan's End",
"24": "Thundergard Stadium",
"25": "Shipwreck Falls",
"27": "Brawlball2",
"28": "Shadowscar Landing",
"29": "Small Wasteland",
"31": "Shrek's Muddy Swamp",
"33": "The Wasteland",
"35": "Shrek's Swamp",
"39": "Big Brawlball Arena",
"40": "The Enigma",
"42": "Small Fortress of Wolves",
"43": "Blackguard Keep",
"45": "Dev Grid",
"47": "Mammoth Fortress",
"49": "Short Side",
"50": "Pillars",
"51": "Pit",
"53": "Brawlball_4_30",
"54": "Wally",
"55": "Big Titan's End",
"56": "Big Thundergard Stadium",
"57": "Big Twilight Grove",
"58": "Big Great Hall",
"59": "Big Lost Labyrinth",
"62": "Small Thundergard Stadium",
"63": "Small Mammoth Fortress",
"64": "Small Blackguard Keep",
"65": "Small Great Hall",
"66": "Plain",
"67": "Small Titan's End",
"68": "Danger Zone",
"70": "The Fangwild",
"71": "Wheel",
"72": "Chute",
"73": "Lost Labyrinth",
"74": "Big Dodgebomb Arena",
"75": "Catch Bombs",
"76": "Miami Dome",
"81": "Small Grumpy Temple",
"84": "Color Platforms",
"89": "Tutorial 1",
"90": "Tutorial 2",
"91": "Tutorial 3",
"93": "Sanctuary",
"94": "Small Brawlhaven",
"95": "Small Enigma",
"96": "Big Enigma",
"97": "Big Shipwreck Falls",
"98": "Big Brawlhaven",
"99": "Elysium",
"100": "Small Fangwild",
"101": "Competitive Grumpy",
"102": "Small Lost Labyrinth",
"103": "Spike",
"104": "Small Cave 2",
"105": "Temple Climb",
"106": "Paintbrawl",
"110": "Flag Battle",
"112": "Demon Island CTF",
"115": "Plains of Passage",
"116": "Crazy Shipwreck Falls",
"117": "Crazy Fangwild",
"118": "Crazy Titan's End",
"119": "Floor is not Lava",
"120": "Crazy Thundergard Stadium",
"121": "Xull's Murder Box",
"123": "Kung Foot Arena",
"124": "Apocalypse",
"125": "Big Crazy Fangwild",
"126": "Fangwild Dodgebomb",
"127": "Small Galvan Prime",
"128": "Big Miami Dome",
"129": "Horde",
"130": "Under the Canopy",
"131": "Tree Fort",
"132": "Ring",
"135": "Demon Island",
"136": "Big Crystal Temple",
"137": "Crystal Temple",
"138": "Temple Ruins",
"139": "Galvan Prime",
"140": "Synthwave Kung Foot",
"141": "Sun Drive City",
"143": "Spirit Realm Showdown",
"144": "Lich's Tomb",
"146": "Walker Attack!",
"147": "Hiding Plats 2 Electric Boo",
"148": "Small Sun Drive City",
"150": "FeudingFlats",
"151": "Spirit Realm",
"152": "World's End Arena",
"153": "Big World's End Arena",
"154": "Divine Spirit Showdown",
"174": "World's End",
"175": "The Turtles' Lair",
"176": "Small Plain",
"177": "Small Turtles' Lair",
"178": "Fortress of the Lions",
"180": "Siege of Lions",
"184": "Suzaku Castle Walls",
"185": "Suzaku Castle",
"186": "Void Minor",
"187": "Void Major",
"188": "Cannonball Mania",
"190": "The Wasteland Showdown",
"191": "Bustling Side Street",
"210": "Fabled City",
"211": "Small Fabled City",
"212": "Western Air Temple",
"214": "Little Boat",
"215": "Frozen Plains",
"216": "Florence Rooftop",
"217": "Florence Terrace",
"220": "Shorwind Fishing Port",
"221": "Thundergard Sands",
"222": "Western Air Temple Brawl",
"223": "Mishima Dojo",
"226": "Nightmare Horde",
"227": "TEKKEN Brawl",
"229": "Small Terminus",
"231": "Terminus",
"232": "Bikini Bottom",
"233": "Small World's End",
"234": "Starlight Falls",
"235": "Crumbling Chasm",
"236": "Apocalyptic Chasm",
"237": "Mustafar",
"238": "Crumbled Chasm",
"242": "Theed Power Generator",
"246": "Small Theed Generator",
"249": "Mos Eisley Spaceport",
"250": "Flipped90BP6GiantSword",
"251": "TutorialBP6GiantSword",
"252": "NTLost Labyrinth",
"253": "Tutorial Fortress of the Lions",
"254": "NTLostLab2",
"255": "Mustafar",
"258": "Old Ivaldi Mine",
"263": "Dragon Port",
"266": "Castle Batavia",
"269": "Shiganshina District",
"271": "Shiganshina District Brawl"
}

LEVELS = {int(k): v for k, v in _RAW.items()}
